# Numpy
***
Numpy is a fundamental library for scientific computing for python. It provides support for arrays and matrice, along with collection of mathematical functions to operate on these data structures. In this module, i will note down basics of Numpy, focusing on arrays and vectorized operations.

## Create 1-D array using Numpy
***

In [2]:
import numpy as np
arr1 = np.array([1,2,3,4,5])
print(arr1)
## type of arr1
print(type(arr1))
## check dimensions of arr1
print(arr1.shape)
## For 1-D array only element count is shown not row and column hence it shows (element_count,)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [5]:
## To convert 1-D array into two 2-D
arr2 = arr1.reshape(1,5) ## row,column
print(arr2)
arr2 = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]]) ## 3x3 matrix or array
print(arr2)

[[1 2 3 4 5]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [14]:
## range function to create array
arr1 = np.arange(1,16).reshape(3,5) #create 3x3 matrix as above but without manually adding them
print(arr1)

## to create unit matrix
print(np.ones((3,3)))

## To create identity matrix
print(np.eye(3)) ## only one dimenstion as identity can be created on square matrix alone

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## Vectorized operations
***

In [19]:
## Vector operations on matrix
arr1 = np.arange(1,16).reshape(3,5)
arr2 = np.arange(-1,-16,-1).reshape(3,5)

## addition
print("addition", arr1+arr2)

## subtraction
print("subtraction", arr1-arr2)

## multiplication 
print("multiplication",arr1*arr2)

## division
print("division", arr1/arr2)

addition [[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
subtraction [[ 2  4  6  8 10]
 [12 14 16 18 20]
 [22 24 26 28 30]]
multiplication [[  -1   -4   -9  -16  -25]
 [ -36  -49  -64  -81 -100]
 [-121 -144 -169 -196 -225]]
division [[-1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1.]]


## Universal functions
***

In [20]:
arr1 = np.arange(1,16).reshape(3,5)
## square root
print(np.sqrt(arr1)) 
## exponential or antilog
print(np.exp(arr1))
## sin
print(np.sin(arr1))
## log
print(np.log(arr1))

[[1.         1.41421356 1.73205081 2.         2.23606798]
 [2.44948974 2.64575131 2.82842712 3.         3.16227766]
 [3.31662479 3.46410162 3.60555128 3.74165739 3.87298335]]
[[2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
  1.48413159e+02]
 [4.03428793e+02 1.09663316e+03 2.98095799e+03 8.10308393e+03
  2.20264658e+04]
 [5.98741417e+04 1.62754791e+05 4.42413392e+05 1.20260428e+06
  3.26901737e+06]]
[[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
 [-0.2794155   0.6569866   0.98935825  0.41211849 -0.54402111]
 [-0.99999021 -0.53657292  0.42016704  0.99060736  0.65028784]]
[[0.         0.69314718 1.09861229 1.38629436 1.60943791]
 [1.79175947 1.94591015 2.07944154 2.19722458 2.30258509]
 [2.39789527 2.48490665 2.56494936 2.63905733 2.7080502 ]]


## Slicing & Indexing
***

In [26]:
arr1 = np.arange(1,16).reshape(3,5)
## to get any row
print(arr1[0])
## to get last row
print(arr1[-1])
## to get any row or column
print(arr1[0][4])
## to get row and column in range
print(arr1[1:,:2])

[1 2 3 4 5]
[11 12 13 14 15]
5
[[ 6  7]
 [11 12]]


## Statistical operations
***

In [29]:
arr1 = np.array([1,2,3,4,5])

std = np.std(arr1)
print(F"Standard deviation: {std}")
mean = np.mean(arr1)
print(F"Mean: {mean}")
median = np.median(arr1)
print(F"Median: {median}")
variance = np.var(arr1)
print(F"Variance: {variance}")
## Normalized data
normalize = (arr1-mean)/std
print("Normalized data, ", normalize)

Standard deviation: 1.4142135623730951
Mean: 3.0
Median: 3.0
Variance: 2.0
Normalized data,  [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


## Logical operations (useful in Pandas)
***

In [33]:
data = np.array([1,2,3,4,5,6,7,8,9,10])
data[data > 5]
data[(data>5) & (data < 8)]

array([6, 7])